### ISSUE TITLE
specifying filetypes fails with `buildifier.sh: line 58: FIND_PATH_EXCLUDES: unbound variable`

### ISSUE THREAD

**Issue by garymm** [thompsonja/bazel-buildifier#5]
My config:

```yml
    runs-on: ubuntu-latest
...
      - name: bazel buildifier
        uses: thompsonja/bazel-buildifier@v0.4.0
        with:
          filetypes: bazel,bzl
```

https://github.com/Astera-org/obelisk/runs/8141843331?check_suite_focus=true

Works fine if I remove `filetypes`
